### PR TITLE
Replacing firmware links for TG-1 (VANT-5) with internode ones

### PR DESCRIPTION
**Pull request by nutterthanos**
Old iinet firmware on the ftp server has been deleted for this device. So changing it to internode ones but don’t even know if it is the exact same md5 or something.

### CODE REVIEW

**Comment by kevdagoat** [comment]
Please replace with internode firmware

**Comment by nutterthanos** [comment]
Ok

**Comment by nutterthanos** [comment]
Rip i have to

**Comment by nutterthanos** [comment]
rip can’t find a firmware file for 15.32.1509-ver1.4 on iinet or internode site

**Comment by nutterthanos** [comment]
Ok all done ready to merge.

**Comment by nutterthanos** [comment]
Well the iinet and internode ftp are the same

**Comment by LuKePicci** [comment]
I have that old missing RBI, but, we already have similar versions available, I think it could be worth keeping a copy of that old version if it would have been the only type 2 one or the only R15 one, and this is not the case. @fru1tl00p is probably able to confirm which one is rootable or not.

I would not keep the "please share" message

**Comment by kevdagoat** [comment]
Looks good

**Comment by nutterthanos** [comment]
> I would not keep the "please share" message

?

**Comment by LuKePicci** [comment]
@nutterthanos For the old 1.4 firmware, you kept a message saying:
> No RBI available, this version has been found on some devices. If you have it on your device please share a dump!

However this RBI was available in the past, and actually I have it. What should we do in such cases? Of course we cannot upload in a git repo all old firmwares for which URL's get broken. It does not scale. Will talk about this issue in a dedicate thread.

Also, you wrote nothing for 1.9.2, are there any RBI for that one?

**Comment by nutterthanos** [comment]
> Also, you wrote nothing for 1.9.2, are there any RBI for that one?

@LuKePicci I did not need to change it since its the latest firmware and its not a dead link unlike the other links.
See PR #24

**Comment by LuKePicci** [comment]
Oh, my bad, the diff viewer was cutting the line with the URL. All good 👍 

Da: nutterthanos
Inviato: sabato 20 luglio 2019 03:49
A: kevdagoat/hack-technicolor
Cc: Luca Piccirillo; Mention
Oggetto: Re: [kevdagoat/hack-technicolor] Replacing firmware links for TG-1(VANT-5) with internode ones (#26)

Also, you wrote nothing for 1.9.2, are there any RBI for that one?
@LuKePicci I did not need to change it since its the latest firmware and its not a dead link unlike the other links.
See PR #24

**Pull request merged**
