### PR TITLE
Revert "Simplify Introduction"

### PR DESCRIPTION
**Pull request by flywire**
Reverts kevdagoat/hack-technicolor#21

### CODE REVIEW

**Comment by kevdagoat** [comment]
I presume that if we do not like the simple home page, we can just merge this?

**Comment by kevdagoat** [comment]
Probably not really needed as the stable branch will have the old home page in it until I sync the branches

**Comment by LuKePicci** [comment]
The idea of moving Types definitions away from the home page is fine but we still need such definitions somewhere otherwise how could someone tell us which type its new firmware is of?

I think we can move the whole part starting at “We conventionally define” to a dedicated section at the beginning of the firmware repo page. So if people don’t care of knowing what “Type N” means they can still follow the guide skipping some details. But we definitely need to keep such details somewhere. The first time I wrote that part I had the problem of understanding what was “Type 1/2/3” meaning because it was not explained elsewhere.

________________________________
Da: Kevdagoat <notifications@github.com>
Inviato: Monday, July 15, 2019 1:09:26 AM
A: kevdagoat/hack-technicolor
Cc: Subscribed
Oggetto: Re: [kevdagoat/hack-technicolor] Revert "Simplify Introduction" (#22)


I presume that if we do not like the simple home page, we can just merge this?

**Comment by kevdagoat** [comment]
@LuKePicci I think a table at the bottom of the index page with type definitions sounds good

**Comment by flywire** [comment]
Main concepts:
- Two banks with firmware, active and inactive
- Type 2 directly rootable
- Type 1 is not directly rootable so load Type 2 then root other bank
- Type 3 has more complicated process to load Type 2
- Type ??? is unknown

**Comment by LuKePicci** [comment]
Table is fine, not sure the index is the best place thou. Someone who come on the repo page from google will not see type definition and won’t be able to get an idea of what types are.

________________________________
Da: Kevdagoat <notifications@github.com>
Inviato: Monday, July 15, 2019 1:32:12 AM
A: kevdagoat/hack-technicolor
Cc: Luca Piccirillo; Mention
Oggetto: Re: [kevdagoat/hack-technicolor] Revert "Simplify Introduction" (#22)


@LuKePicci<https://github.com/LuKePicci> I think a table at the bottom of the index page with type definitions sounds good

**Comment by flywire** [comment]
Agree. Keep index simple so users can choose Type and firmware and put detail elsewhere. Still think the five points might be simpler than a table.

**Comment by LuKePicci** [comment]
@flywire your description is not precise enough
What you describe as Type 1 is actually anything different from Type 2. We can also say

> Type **3** is not directly rootable so load Type 2 then root other bank

and that statemant is still true. The difference between Type 1 and 3 is the way by which you get a Type 2 flashed.

**Comment by kevdagoat** [comment]
Gimme a sec and I’ll push the changes so you can have a look

**Comment by flywire** [comment]
Tried to describe it with the bold:
> * Type 3 has **more complicated process** to load Type 2

Anyway, idea is present concept and put detail elsewhere.

**Comment by kevdagoat** [comment]
See latest pr

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
@LuKePicci @flywire Keep in mind that the guide that the 'normal' people see is the stable branch. So at the moment, if you look at https://hack-technicolor.rtfd.io , none of the changes are there

**Comment by flywire** [comment]
> 'normal' people see is the stable branch

I understand.

> See latest pr

Where is that?

**Comment by kevdagoat** [comment]
@flywire was making sure :)

Here:
https://hack-technicolor.readthedocs.io/en/latest/

or here:
https://github.com/kevdagoat/hack-technicolor/commit/cc33d6c2eb325a366edd68808465e4d4e567acba

**Comment by flywire** [comment]
OK. Finesse the definitions a little, mainly removing 'if any'.

**Comment by flywire** [comment]
Maybe put 'What are these Types?' in an information box.

**Comment by LuKePicci** [comment]
I agree with @flywire about the idea of moving away that part from the index. I think you can move the precise definitions in the repo page and merge the short concepts he previously suggested with the "where to start points". So:

Type 2 is directly rootable, -> see HackType1/2
Type 1 is not directly rootable so flash Type 2 -> see HackType1/2
Type 3 is the same as Type 1 but has more complicated process to load Type 2 -> see TFTP **and** failboot if needed
Type ??? is unknown, do the same as of Type 3 until you know more--> see TFTP **and** failboot if needed.

If you omit the part about failboot here for type 3/??? people won't know where to go after TFTP flash.

**Comment by kevdagoat** [comment]
@LuKePicci Ok, will do

**Comment by kevdagoat** [comment]
@LuKePicci @flywire 

e49e44b178006c8b419aa1a3d884b1793f709034

**Comment by flywire** [comment]
Don't need 'Key points' - covered with 'See the README for more info'

**Comment by kevdagoat** [comment]
@flywire Done

**Comment by flywire** [comment]
@kevdagoat - radical.

(I actually meant the heading not the entire section. Still, consider both options.)

**Comment by kevdagoat** [comment]
Hahahaha
Ok then

Sent from Mail for Windows 10

**Comment by kevdagoat** [comment]
I think this can be closed now. @flywire @LuKePicci Are you happy with the current state of index.md?

**Comment by flywire** [comment]
Couple of minor formatting issues - seems md renders different to io.

**Comment by kevdagoat** [comment]
Have a look now

Sent from Mail for Windows 10

**Comment by flywire** [comment]
My comments (I can't find the pencil icon for that commit).

I like as an example:
1. https://github.com/kevdagoat/hack-technicolor/commit/6e1b0b051f04238f3027456244dd91193abf975a#diff-1a523bd9fa0dbf998008b37579210e12L3 as a single line
2. https://github.com/kevdagoat/hack-technicolor/commit/6e1b0b051f04238f3027456244dd91193abf975a#diff-1a523bd9fa0dbf998008b37579210e12L16 (lines 14 to 16) as decision followed by action on same line

(Hopefully clear enough.)

**Comment by kevdagoat** [comment]
Have a look now.

Btw the page is called index.md

Sent from Mail for Windows 10

**Comment by flywire** [comment]
So user has been through `Firmware Repository` and not found their firmware. Why not?

- Out of scope: How does the user know?
- Even if out of scope they might be able to upgrade firmware to usable type
- Unknown type

**Comment by flywire** [comment]
This heading [BOOT-P recovery mode (TFTP flashing)](https://hack-technicolor.readthedocs.io/en/latest/Recovery/#boot-p-recovery-mode-tftp-flashing) and any links to it need to be consistent throughout guide.

**Comment by LuKePicci** [comment]
@flywire everything about types should be fine now.

**Comment by flywire** [comment]
@LuKePicci I'll tweak 'Where to Start'
1. Still not clear how user identifies `Homeware 10.x`
2. Rendering issue with https://hack-technicolor.readthedocs.io/en/latest/ - 4 points show as 8 points (rather than indented)

**Comment by LuKePicci** [comment]
Do you have any suggestion on how to identify 10.x and older versions? Usually firmware version appears in the gateway info page (like this https://support.zen.co.uk/kb/Uploads/Images/Technicolor/TG582/tg582-home.png) but it's not true in general. ISP may customize version numbers hiding real Homeware release version or even replace the default UI look'n'feel (for instance https://gstatic02.dyndns.it/wp-content/uploads/2016/12/gestione-smart-modem-tim-dyndns.png) so I have no better hint to give in this direction. In general, if you don't know which is your current version you are unable to proceed, even for newer firmwares so I wouldn't bother so much about that.

**Comment by kevdagoat** [comment]
I think this can be closed now...

**Pull request closed without merging**
