### PR TITLE
Add VBNT-1 OSCK

### PR DESCRIPTION
**Pull request by nutterthanos**
I figured out how to create the osck
but can't really do anything with it unless the firmware gets an update.

### CODE REVIEW

**Comment by LuKePicci** [comment]
Oh, thank you, I didn't notice it we ware missing this. Remember to let me know as soon as iiNet pushes an update to 18.3.0157-3-2-1.

**Comment by LuKePicci** [comment]
Please try to include this in https://github.com/Ansuel/Decrypt_RBI_Firmware_Utility/blob/master/src/main/board.java as well.

**Comment by nutterthanos** [comment]
Ok but how you add it to that file when this file is encoded?

**Comment by nutterthanos** [comment]
Like here is an example from a DJN230 
222C4DC4A9DF952B02D5A489A112CF5E29AAEDF86ADB634410D6721F15F451E4
And the OSCK I added is encoded

**Comment by LuKePicci** [comment]
Read comments in this page: https://github.com/kevdagoat/hack-technicolor/commit/21e513b6d5f045a6df8c6d70f0786fcf7650d5cd

**Pull request merged**
